### ISSUE TITLE
resourcepack.tgz and rendertest19.tgz not gzip files error

### ISSUE THREAD

**Issue by finndo77** [IncredibleHolg/OverviewerDocker#3]
receiving this (truncated) output from running create-test.sh

```
Step 18/19 : RUN cd /WRK &&  tar -zxvf resourcepack.tgz  -C /WRK/ && tar -zxvf rendertest19.tgz -C /WRK/ &&    rm -f rendertest19.tgz resourcepack.tgz
 ---> Running in 837283ea2c8f

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c cd /WRK &&  tar -zxvf resourcepack.tgz  -C /WRK/ && tar -zxvf rendertest19.tgz -C /WRK/ &&    rm -f rendertest19.tgz resourcepack.tgz' returned a non-zero code: 2
```

I tried opening the files from the desktop (linux mint 20) and received the same error from both.  Appreciate any info, thanks!

**Comment by IncredibleHolg** [comment]
Hi @finndo77 
Testimage.Dockerfile, rendertest.py and create-test.sh is a very crude testing setup.
It copies a texturepack and a worldfile into the Image below /WRK and you can run your test map builds.

**Comment by IncredibleHolg** [comment]
@finndo77 Hi,
I updated and cleaned up the project.
The problem with the archives is missing LFS support on your git client side.
I Updated the information in the documentation.
The resource pack is removed ( it belongs to Mojang ). I added scripting to create it during the build.
